### ISSUE TITLE
Could be derived from gdey027T91

### ISSUE THREAD

**Issue by benjamo** [martinberlin/CalEPD#12]
https://github.com/martinberlin/CalEPD/blob/81ce16eb04b6dc5c2564eeeca65f5c849d498ecf/include/goodisplay/touch/gdey027T91T.h#L27

I think you could derived from gdey027T91, so wouldn´t need to change for example the adjustments from the last commit.

**Comment by martinberlin** [comment]
Probably could, but the T version has different initialization constructor since expects Touch to be injected as a parameter.
If you think that you can make it simpler and more convenient please make a PR and I will test it.

**Comment by martinberlin** [comment]
Unless I'm missing something we can close here. If you find a nicer way to do it @benjamo please make a merge-request that is the way we collaborate on open-source
