### ISSUE TITLE
Missing driver component in ESP IDF v5?

### ISSUE THREAD

**Issue by thebitguru** [martinberlin/CalEPD#14]
Hi, @martinberlin!

I am starting to get back into my project. I saw that ESP IDF v5 [requires explicitly including the `driver` component](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/build-system.html#specify-component-requirements-explicitly), which I didn't see in the [CMakeList](https://github.com/martinberlin/CalEPD/blob/master/CMakeLists.txt). How did you get around this without including the `driver` component? Without that, I get the following error.

```
In file included from components/CalEPD/epdspi.cpp:2:
components/CalEPD/include/epdspi.h:2:10: fatal error: driver/spi_master.h: No such file or directory
    2 | #include "driver/spi_master.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by martinberlin** [comment]
Yes correct. This needs to be added. I didn’t got the error since in the development repository is adding also touch component 
https://github.com/martinberlin/cale-idf/blob/master/components/FT6X36-IDF/CMakeLists.txt

Will include it in next release today. Then I can close this one as completed.

**Comment by thebitguru** [comment]
Ah, I see. That makes sense. I am able to continue by including `driver`.

I am also getting an error related to `portTICK_RATE_MS` not being defined anymore, and need to track it down. Maybe you already happen to know what's about. This is in [`epd4spi.cpp`](https://github.com/martinberlin/CalEPD/blob/42aab2a6b896b3b850e0d571d895e51005d7f9ad/epd4spi.cpp#L386).

I am always amazed by your response times. Keep up the great work!

**Comment by martinberlin** [comment]
Thanks. That one is also fixed in this PR
https://github.com/martinberlin/cale-idf/pull/94 Coming today in new release. 
For that you can also go to menuconfig -> Component config -> FreeRTOS -> Kernel 

and activate "Backward compatibility"

**Comment by martinberlin** [comment]
Just git pull origin.
Please close this one if it compiles now without errors. Thanks!

**Comment by thebitguru** [comment]
That worked. Thanks!
