### ISSUE TITLE
Grayscale support in gdew042t2Grays is no longer working

### ISSUE THREAD

**Issue by thebitguru** [martinberlin/CalEPD#16]
Hi, Martin,

I noticed that the latest gdew042t2Grays.cpp breaks the grayscale support for [the display](https://www.good-display.com/product/226.html). The following block that forces mono mode (also the default mode) displays the "Starting..." text.

```
    display.init(false);
    display.setMonoMode(true);
    display.fillScreen(EPD_BLACK);
    display.setTextColor(EPD_WHITE);
    display.drawString(130, 200, "Starting...");
    display.update();
```

But when I disable the mono mode (i.e., enable grayscale) then it doesn't display anything. Note that I didn't even change the colors in this case to keep it simple.

```
    display.init(false);
    display.setMonoMode(false);
    display.fillScreen(EPD_BLACK);
    display.setTextColor(EPD_WHITE);
    display.drawString(130, 200, "Starting...");
    display.update();
```

Note that in the above code `display` is a very simple wrapper for `Gdew042t2Grays` that only adds additional functions.

Any ideas on what might be going on here? Here is the [datasheet](https://v4.cecdn.yun300.cn/100001_1909185148/GDEW042T2-1.pdf) for reference.

**Comment by martinberlin** [comment]
Hello @thebitguru 
this time you will have to debug it yourself since I do not own anymore (And won't buy anymore SPI epapers)
since I'm focused on helping another projects for a few years.
But last times I tested:
https://github.com/PaperMETAR/FirmwareTinker/blob/master/src/main.cpp
It was working in the demos.

Debug the buffers, check start up commands, I don't think that class has changed anything since last times we checked.

**Comment by martinberlin** [comment]
- Try to print text in one of the Grays
- Try playing around removing Background
- Try also making a small mono-mode update and then make the gray-mode update to see if there is any initial initialization wakeUp command that is needed

**Comment by thebitguru** [comment]
Thanks for those tips. I will experiment over the next few days and report back. I will submit a PR if I am able to propose a fix.

**Comment by martinberlin** [comment]
Great! 
Thanks for your contribution. Now this will be fixed by anyone using this display and you also have your code in the contributors list.
Please close it after checking again that it works as expected.

**Comment by thebitguru** [comment]
Confirmed against master branch. Thanks!

**Comment by martinberlin** [comment]
The @thebitguru I will like to see some pictures/ videos once you finish your creation!
Thanks a lot for choosing our component.

**Comment by thebitguru** [comment]
Will do. Thanks for all your work on this library!
