### ISSUE TITLE
Grayscale in Good Display GDEW042t2

### ISSUE THREAD

**Issue by thebitguru** [martinberlin/CalEPD#7]
Thank you very much for creating this library!  I am working with the [Good Display gdew042t2](https://www.buy-lcd.com/products/42inch-e-inkanel-spi-interface-buy-eaper-display) which supports four gray scales, but I noticed that the library doesn't seem to think that's the case (i.e., it assumes it black and white only).  Is that the case or am I misunderstanding something?

**Comment by martinberlin** [comment]
Thanks guru,
No that’s the case as you mention. But I tried to implement the 3 grayscales in the 7 inches:
https://github.com/martinberlin/cale-idf/wiki/Model-gdew075T7.h#4-gray-version

And I don’t like it. It’s shit grayscales. Only parallel epapers have usable grays.
So if you want to implement it then you are on your own. And you can make a merge request but please call the class with another name and let’s leave one that in just monochrome.

**Comment by thebitguru** [comment]
Thanks for the quick response.  What do you mean by "shit grayscales?" :)

**Comment by martinberlin** [comment]
Well if you open the link you will see for yourself. Using black on this mode is not real black and other 2 are too close to make anything useful. Please make up your mind and either leave this open and plan to add this yourself or close it if you don’t want to implement it.

**Comment by thebitguru** [comment]
I see. Let's leave this open. I'll plan to add this as a separate class like you suggested. Thanks!

**Comment by martinberlin** [comment]
Great, I would help you testing but sadly I don't have anymore one of those models of epaper.
You can check how is done in this class: [gdew075T7Grays](https://github.com/martinberlin/CalEPD/blob/master/models/gdew075T7Grays.cpp)

**Comment by martinberlin** [comment]
Implemented in this class:
https://github.com/martinberlin/CalEPD/blob/master/models/gdew042t2Grays.cpp
